### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by hamidafghan** [hamidafghan/laravel-mention-example#1]
@phptinker
```php
echo "It is very test issue";
```

**Comment by phptinker** [comment]
@hamidafghan, here's the evaluated code:

```
It is very test issue
```

<details>
<summary>We evaluated this code</summary>

```php
echo "It is very test issue";
```
</details>

Check out [Tinkerwell](https://tinkerwell.app) for even easier code evaluation.

**Comment by hamidafghan** [comment]
@phptinker 
```php
$numbers = collect([1,2,3,4,5,6,7]);
print_r($numbers);
```
